[package]
name = "meteofrance-forecast"
version = "0.1.0"
authors = ["Maxime Poncet <maxime.poncet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restson = "^0.6"
serde = "^1.0"
serde_derive = "^1.0"
